name: Build
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          platform: linux
          arch: x64
        - os: ubuntu-22.04-arm64
          platform: linux
          arch: arm64
        - os: macos-14
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: windows-2022
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: holesail-${{ matrix.platform }}-${{ matrix.arch }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: npm install -g pkg
    - run: npm install --omit=dev
    - run: |
        if [ "${{ matrix.platform }}" == "linux" ]; then
          pkg . --targets node16-linux-${{ matrix.arch }} --output builds/holesail-${{ matrix.platform }}-${{ matrix.arch }}
        elif [ "${{ matrix.platform }}" == "darwin" ]; then
          pkg . --targets node16-macos-${{ matrix.arch }} --output builds/holesail-${{ matrix.platform }}-${{ matrix.arch }}
        elif [ "${{ matrix.platform }}" == "win32" ]; then
          pkg . --targets node16-win-${{ matrix.arch }} --output builds/holesail-${{ matrix.platform }}-${{ matrix.arch }}
        fi
      shell: bash
    - run: |
        if ($env:PLATFORM -eq "win32") {
          pkg . --targets node16-win-$($env:ARCH) --output builds/holesail-$($env:PLATFORM)-$($env:ARCH)
        }
      shell: pwsh
    - uses: actions/upload-artifact@v4
      with:
        name: holesail-${{ matrix.platform }}-${{ matrix.arch }}
        path: builds/*
  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          merge-multiple: true
      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: builds
