name: Build
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          platform: linux
          arch: x64
        - os: ubuntu-22.04-arm64
          platform: linux
          arch: arm64
        - os: macos-14
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: windows-2022
          platform: win32
          arch: x64
        - os: windows-2022
          platform: win32
          arch: arm64
    runs-on: ${{ matrix.os }}
    name: holesail-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
    - run: npm install -g nexe
    - run: npm install
    - run: |
        if [ "${{ matrix.platform }}" == "linux" ]; then
          nexe index.js -r "includes/*" --build --target linux-${{ matrix.arch }}-20.14.0 --verbose
        elif [ "${{ matrix.platform }}" == "darwin" ]; then
          nexe index.js -r "includes/*" --build --target darwin-${{ matrix.arch }}-20.14.0 --verbose
        elif [ "${{ matrix.platform }}" == "win32" ]; then
          nexe index.js -r "includes/*" --build --target windows-${{ matrix.arch }}-20.14.0 --verbose
        fi
    - uses: actions/upload-artifact@v4
      with:
        name: holesail-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
        path: builds/*
  merge:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          merge-multiple: true
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilds
          path: prebuilds
